### ISSUE TITLE
Sprint 1 Backlog are not the tasks...

### ISSUE THREAD

**Issue by luizperes** [keigo135/keigo135.github.io#1]
Hi keigo,
Good job on your Product Backlog!

On your Sprint 1 Backlog, though... the backlog items should be on the leftmost side under `Sprint Backlog`... after that, you should break them in tasks, just like that: 

![screen shot 2016-11-10 at 3 05 03 pm](https://cloud.githubusercontent.com/assets/6173065/20197994/1c9decae-a757-11e6-991b-c8dde20266c8.png)

Remember that the items `TODO`, `In Progress`, `Done` and `Impediments` have the tasks (which are small tasks from the Backlog/Stories)...

A story is a big task, a task makes part of a story... in this way:

Story: `104 - Project Management`

Tasks: `Study for Quiz`, `Read Wikipedia`, `Take Online Course 1/4`, `Take Online Course 2/4`, `Take Online Course 3/4`, `Take Online Course 4/4`, `Take Quiz`

A story is a __group__ of tasks :)

Good job, though!

**Comment by keigo135** [comment]
Hi Luiz,

I misunderstood what you taught us. I've already fixed the backlog of sprint 1. Let me know if there's a wrong part. 

Have a great weekend =)

**Comment by luizperes** [comment]
Hi Keigo,
it looks very good now!
Thank you!
